References
winter-telescope/mirar pull request #582
Opened 2023-08-02 17:08 UTC by virajkaram

2023-08-02 21:42 UTC, robertdstein requested changes
The main thing is the lack of docstrings. We do documentation built with sphinx, so should follow the sphinx style: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

that means basically always have :param for each param, plus :return

2023-08-02 21:42 UTC, robertdstein commented on mirar/io.py
> +def open_fits(path: str | Path, **fits_open_kwargs) -> tuple[np.ndarray, fits.Header]:
What are the `fits_open_kwargs` that need to be passed?

2023-08-02 21:42 UTC, robertdstein commented on mirar/io.py
> +    path = str(path)
Why do you turn the path into a string first?

2023-08-02 21:42 UTC, robertdstein commented on mirar/io.py
> +        [str | Path, Optional[dict]], tuple[np.ndarray, fits.Header]
Is this righ? open_f can work on a dictionary?

2023-08-02 21:42 UTC, robertdstein commented on mirar/pipelines/winter/generator.py
> +    logger.debug(kwargs)
this is a bad logger message. If you want it please add some text explaining what you are printing e.g `wfau kwargs: {kwargs}`

2023-08-02 21:42 UTC, robertdstein commented on mirar/pipelines/winter/generator.py
>          components_image_dir.mkdir(parents=True)
make this a one-liner to avoid race conditions

2023-08-02 21:42 UTC, robertdstein commented on mirar/processors/astromatic/swarp/swarp.py
> +                shutil.copy(temp_output_image_path, output_image_path)
swarp should not save images, that should only happen in imagesaver

2023-08-02 21:42 UTC, robertdstein commented on mirar/processors/zogy/zogy.py
> +    TODO: This should be in wirc?
Please move to wirc

2023-08-02 21:42 UTC, robertdstein commented on mirar/processors/zogy/zogy.py
> +    TODO: Catalog purifier for the summer data. This should probably be in summer.
move to summer

2023-08-02 21:42 UTC, robertdstein commented on mirar/processors/zogy/zogy.py
> +    TODO: This should be in sedmv2?
move to sedmv2

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/base_reference_generator.py
> +        :return: ref image
you do not return a ref image, you return two fits.HDUs

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/utils.py
> +        ra:
Add docstring

(style :param / :return)

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/utils.py
> +        primary_header:
Add docstring

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/utils.py
> +    Args:
add docstring

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +        UKIDSSClass
Add :return

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    def get_surveys(self, ra: float, dec: float) -> list[MOCSurvey]:
Add docstring

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    def get_query_crds(
add :return

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +        savedir: Directory to save the images.
:param and add :return

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +                crd = query_crds[ind]
this line is redundant?

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    def run_query(self, image: Image):
docstring

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    and ingest it into a database.
docstring with :params

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +def check_query_exists_locally(
Add type hints

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    # TODO - run a joint query to get the savepaths
Is this still relevant?

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +
Add :return

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +
Add return and :params (explain)

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    def get_surveys(self, ra: float, dec: float) -> list[MOCSurvey]:
docstrings

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_query.py
> +    def get_query_class(self) -> BaseWFAUClass:
docstrings

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_stack.py
> +
returns image batch

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_stack.py
> +
also, explain what the cuts are

2023-08-02 21:42 UTC, robertdstein commented on mirar/references/wfcam/wfcam_stack.py
> +        """
docstring :param/:return

2023-08-04 18:38 UTC, robertdstein requested changes
1 minor change then I'm happy

2023-08-04 18:38 UTC, robertdstein commented on mirar/io.py
> +def open_fits(path: str | Path, **fits_open_kwargs) -> tuple[np.ndarray, fits.Header]:
Just remove this new kwarg and put it directly in open_fits for everyone I think

2023-08-04 18:38 UTC, robertdstein commented on mirar/processors/astromatic/swarp/swarp.py
> +                shutil.copy(temp_output_image_path, output_image_path)
Ok, sounds good

2023-08-04 18:39 UTC, virajkaram commented
I wouldn't do that, it is not fits convention to have missing SIMPLE keywords, but seems to be an issue specifically with UKIRT and we can;t do anything about it..

2023-08-04 18:52 UTC, robertdstein approved these changes

2023-08-04 19:19 UTC, merged