Make PhotCalibrator more generic, add ZP calculation with color term capability
winter-telescope/mirar pull request #736
Opened 2024-01-25 00:00 UTC by virajkaram

2024-01-25 03:15 UTC, saarahhall commented
Closes #664

2024-01-26 00:57 UTC, robertdstein requested changes

2024-01-26 00:57 UTC, robertdstein commented on mirar/pipelines/sedmv2/blocks.py
> +from mirar.processors.photcal.photcal import PhotCalibrator
photcal.photcal is a bad name, please come up with something else

2024-01-26 00:57 UTC, robertdstein commented on mirar/processors/astromatic/sextractor/sextractor.py
> +        if ~self.use_psfex & (self.psf_path is not None):
if (not self.use_psfex) & (self.psf_path is not None):

(I think it's more readable/pep8-y)

2024-01-26 00:57 UTC, robertdstein commented on mirar/processors/photcal/__init__.py
I think is is kinda bad practise, you can't import from processors/photcal without loading these. It could lead to some circular imports in photcal/photcal which is importing from photcal/__init__.py. Please put these in an photcal_errors.py and then import stuff (also the processors in subdirectories) properly to photcal/__init__.py.

2024-01-26 00:57 UTC, robertdstein commented on mirar/processors/photcal/zp_calculator.py
Split into separate files I'd say. Try "one processor/main class per python file, for improved searchability"

2024-01-26 00:57 UTC, robertdstein commented on mirar/zeropoints/zp_calculators.py
what is this?

2024-01-26 00:57 UTC, robertdstein commented on mirar/zeropoints/__init__.py
what is this?

2024-01-26 01:58 UTC, robertdstein approved these changes

2024-01-26 02:19 UTC, merged

2024-01-26 02:23 UTC, saarahhall requested changes

2024-01-26 02:23 UTC, saarahhall commented on mirar/processors/photcal/zp_calculator/color_term_zp_calculator.py
> +            y = matched_img_cat[colname] - matched_ref_cat["magnitude"]
Should be `y = matched_ref_cat["magnitude"] - matched_img_cat[colname]`

2024-01-26 02:23 UTC, saarahhall commented on mirar/processors/photcal/zp_calculator/color_term_zp_calculator.py
> +                matched_img_cat[colname.replace("MAG", "MAGERR")] ** 2
when I try to run this, I get the error `  File "/Users/saarahhall/Desktop/research/mirar/mirar/processors/photcal/zp_calculator.py", line 161, in calculate_zeropoint
    matched_img_cat[colname.replace("MAG", "MAGERR")] ** 2
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saarahhall/miniconda3/envs/mirar/lib/python3.11/site-packages/astropy/table/table.py", line 2055, in __getitem__
    return self.columns[item]
           ~~~~~~~~~~~~^^^^^^
  File "/Users/saarahhall/miniconda3/envs/mirar/lib/python3.11/site-packages/astropy/table/table.py", line 264, in __getitem__
    return OrderedDict.__getitem__(self, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'MAGERRAPER_4.0' ` Is this an issue on my end or have you tested this function out?