fit for color + zeropoint using x and y uncertainties
winter-telescope/mirar pull request #762
Opened 2024-02-13 00:08 UTC by saarahhall

This tiny PR utilizes `scipy.odr` inside `ZPWithColorTermCalculator` to fit a line using the x and y uncertainties in the color vs. differential mag plot. 

Room for improvement: for the ODR to work, we can't use data with 0 uncertainty (in x or y). In quite a few lines of code, I added some code that removes those points with 0 uncertainty. This could certainly be compressed. But also, 0 uncertainty in x would only happen if the reference catalog reports 0 uncertainty for both magnitudes of interest, which should be a red flag anyways. So, I feel this cut belongs somewhere else... in a reference catalog purifier? But one that everyone should use... let me know your thoughts @virajkaram @robertdstein

2024-02-13 18:02 UTC, robertdstein requested changes

2024-02-13 18:02 UTC, robertdstein commented on mirar/processors/photcal/zp_calculator.py
> +                    f"mean: {zp_mean}, median: {zp_med}, std: {zp_std}"
pit some limits on this e.g `{zp_mean:.2f}`

2024-02-13 18:02 UTC, robertdstein commented on mirar/processors/photcal/zp_calculator.py
> +def line_model(data, slope, intercept):
returns float

2024-02-13 18:02 UTC, robertdstein commented on mirar/processors/photcal/zp_calculator.py
> +    """linear model to hand to scipy curve_fit"""
describe arguments

2024-02-13 18:02 UTC, robertdstein commented on mirar/zeropoints/zp_calculators.py
why is this empty?

2024-02-14 18:26 UTC, robertdstein approved these changes

2024-02-14 23:30 UTC, virajkaram commented on mirar/processors/photcal/zp_calculator/color_term_zp_calculator.py
> +            where_zero_y = np.where(np.array(y_err) == 0)[0]
Probably cleaner with `non_zero_mask = (np.array(y_err)==0) | (np.array(x_err)==0)`

2024-02-14 23:31 UTC, virajkaram commented on mirar/processors/photcal/zp_calculator/color_term_zp_calculator.py
> +            where_zero_y = np.where(np.array(y_err) == 0)[0]
And then `x_err = x_err[non_zero_mask]` and so on, will have to convert all lists to numpy arrays

2024-02-14 23:34 UTC, virajkaram reviewed
minor change

2024-02-15 18:57 UTC, merged